### ISSUE TITLE
Please consider fixing errors reported by adapter checker

### ISSUE THREAD

**Issue by mcm1957** [Homemade-Disaster/ioBroker.netatmo-energy#13]
Adapter CHecker reported the following erros / warning for 2.6.0.
Please consider fixing them for the **next** release:

[E518] "@alcalzone/release-script" is used, but ".releaseconfig.json" not found
[W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package
[W505] setTimeout found in "main.js", but no clearTimeout detected

**Comment by Homemade-Disaster** [comment]
Error corrected in 2.6.1
