### ISSUE TITLE
Get no Data, Token is missing

### ISSUE THREAD

**Issue by andre2308** [Homemade-Disaster/ioBroker.netatmo-energy#6]
Hi Homemade-Disaster, 

i started with an new Installation of iobroker an with your Adapter. 
Unfortunately the adapter didn´t get any Token´s from Netatmo.

I verifiyed the credentials with a Blocky  i found in the forum.

1. Start with an new installation of the Adapter
2. Add Creditentials in Settings

**Screenshots & Logfiles**  
Log are taken with adapter in silly mode.
![image](https://user-images.githubusercontent.com/16503629/177352815-9bfb8def-7dfe-4608-b912-7fd4353e510d.png)

**Versions:**  
 - Adapter version: 1.3.1
 - JS-Controller version: 4.0.23
 - Node version: 16.15.1
 - Operating system: Synology DS920+ DSM7.2 with Docker (offical Image from iobroker)

kind regards
André

edit: removed home-ID from log

**Comment by Homemade-Disaster** [comment]
Hello,

on my side, it is working correctly. 
Please check if you have created the APP.

You can find the detailed description in the README.
https://github.com/Homemade-Disaster/ioBroker.netatmo-energy/blob/master/docs/en/README.md

Pleas check if the "client ID" and "client secret" i
s correctly inserted in the adapter configuration page.

kind regards

**Comment by andre2308** [comment]
Hi, 

hmm okay. 

I have read the Readme an tryed it again, but with no success.
I keep getting the same error messages as in the screenshot, even if I deliberately use wrong access data,
is it normal that the password field becomes invisible when I try to enter it?

![image](https://user-images.githubusercontent.com/16503629/178340923-b18b3910-bb02-425d-82ec-aa84d32c7574.png)

The credentials are working in an another Node-Red installation and also working with this Blocky in ioBroker: 
https://forum.iobroker.net/topic/41568/stabiles-netatmo-thermostat-blockly-adapter.

I have also tryed an reinstallation of your adapter via npm or Github link via the admin interface. 

btw i have Senetry active, maybe you can see something here.. 

kind regarts

**Comment by prorun26** [comment]
Hallo Zusammen, 
ich habe leider genau das gleiche Problem. 
Meine home_id, client_id und client_secret sind korrekt eingetragen. Dennoch bekomme ich die Meldung "Ich habe keinen Token erhalten" und "Api-Anfrage nicht ok". Habe Testweise einen neuen Netatmo Account angelegt und dort eine App erzeugt (andere home_id, client_id und andere client_secret) - Leider mit gleichen Ergebnis: "Ich habe keinen Token erhalten" + "Api-Anfrage nicht ok". 

Wenn ich den Adapter dann so laufen lasse kommt promt eine Mail: Nach mehreren fehlgeschlagenen Anmeldeversuchen wurde Ihr Konto für die nächsten 10 Minuten gesperrt. Die letzte Anmeldung in Ihrem Konto xyz@xyz.net wurde am 29.08.22, 14:20 in Leipzig, Germany* (ungefährer Standort, abgeleitet von der IP-Adresse: 93.206.13.183) über die Drittanbieter-App ioBroker_Energy mit Ihrem Passwort vorgenommen.
New Connection 	
ioBroker_Energy
28.08.22, 04:50
93.206.13.183
Leipzig, Germany*

Die Abfragen über dev.netatmo.com funktionieren. Wenn ich mit get /homesdata meine Home-ID erhalte und diese dann mit get /homestatus benutze um die Home-ID abzufragen kommt der Response korrekt zurück und ich sehe darin alle meine eigerichteten Thermostate. 

Einen Copy-Paste-Fehler kann ich nach mehrmaliger Kontrolle mit Sicherheit ausschließen. 

Gibt es zu dieser Problematik schon Ansätze oder gar eine Lösung?

**Comment by prorun26** [comment]
Oder werden ggf. nur bei der Übertragung des Passworts diverse Sonderzeichen falsch translitteriert. Das würde zum einen die Mail bzgl der fehlgeschlagenen Anmeldeversuche und auch die Tatsache dass nur Einige unter diesem Fehler leiden erklären!?

**Comment by prorun26** [comment]
Habe jetzt Gelegenheit gehabt verschiedene Sonderzeichen im Passwort auszuprobieren. Daran liegt es offensichtlich nicht.

Weiterhin der gleiche Fehler:
![grafik](https://user-images.githubusercontent.com/112396681/187239602-10b295d8-8812-4bf3-8f44-b6292e970d18.png)

**Comment by ioyeti777** [comment]
Hallo zusammen, ich habe genau das oben beschriebene Problem "API-Anfrage nicht ok" "Ich habe keinen Tokencode erhalten". Home ID, client ID, Client-Secret habe ich alles kopiert, so dass ich da einen Fehler eigentlich ausschließen möchte. Neuinstallation hat auch nix gebracht. Gibt es da Tipps was ich machen kann. Probiere da echt schon lang rum...

**Comment by prorun26** [comment]
Meine Empfehlung ist, das stabile Netatmo Thermostat Blockly von Newpicsel zu verwenden. Da hier keine Antworten mehr kommen sieht es wohl so aus, dass an diesem Projekt nicht mehr weitergearbeitet wird. 

Zudem hat Netatmo folgende Info heraus gegeben: "password token flow will be disabled by Netatmo end of September 2022!" Dh. kommt zu diesem Adapter kein entsprechendes Update funktioniert er ab Oktober grundsätzlich bei niemanden mehr.

**Comment by Homemade-Disaster** [comment]
Hello,

I have released a new version (v2.0.1) of the adapter. This version supports the OAuth2 authentication.
You have to authenticate your account in the adapter config after installing the new version.
