### ISSUE TITLE
"Ich habe keinen Token erhalten" + "Api-Anfrage nicht ok"

### ISSUE THREAD

**Issue by prorun26** [Homemade-Disaster/ioBroker.netatmo-energy#7]
Hallo Zusammen,
meine home_id, client_id und client_secret sind korrekt eingetragen. Dennoch bekomme ich die Meldung "Ich habe keinen Token erhalten" und "Api-Anfrage nicht ok". Habe Testweise einen neuen Netatmo Account angelegt und dort eine weitere App erzeugt (andere home_id, client_id und andere client_secret) - Leider mit gleichen Ergebnis: "Ich habe keinen Token erhalten" + "Api-Anfrage nicht ok".

Wenn ich den Adapter dann so laufen lasse kommt promt eine Mail: Nach mehreren fehlgeschlagenen Anmeldeversuchen wurde Ihr Konto für die nächsten 10 Minuten gesperrt. Die letzte Anmeldung in Ihrem Konto [xyz@xyz.net](mailto:xyz@xyz.net) wurde am 29.08.22, 14:20 in Leipzig, Germany* (ungefährer Standort, abgeleitet von der IP-Adresse: xx.xxx.xx.xxx) über die Drittanbieter-App ioBroker_Energy mit Ihrem Passwort vorgenommen.
New Connection
ioBroker_Energy
28.08.22, 04:50
xx.xxx.xx.xxx
Leipzig, Germany*

Die Abfragen über dev.netatmo.com funktionieren. Wenn ich mit get /homesdata meine Home-ID erhalte und diese dann mit get /homestatus benutze um die Home-ID abzufragen kommt der Response korrekt zurück und ich sehe darin alle meine eigerichteten Thermostate.

Einen Copy-Paste-Fehler kann ich nach mehrmaliger Kontrolle mit Sicherheit ausschließen.
home_id, client_id und client_secret funktionieren über mit dem mittlerweile weitverbreiteten Netatmo Thermostat Blockly Skript von Newpicsel einwandfrei. Ein Fehler in meinen Anmeldedaten oder eine Sperre seitens Netatmo kann also auch grundsätzlich werden.

Gibt es zu dieser Problematik schon Ansätze oder gar eine Lösung?

**Comment by Homemade-Disaster** [comment]
Hallo,

ich habe nun eine neue Version (v2.0.1) erstellt, die die OAuth2 Authentifizierung unterstützt.
Nach der Installation der neuen Version muss die Authentifizierung in der Adapter-Config durchgeführt werden.
