### ISSUE TITLE
password token flow will be disabled by Netatmo nd of September 2022!

### ISSUE THREAD

**Issue by Apollon77** [Homemade-Disaster/ioBroker.netatmo-energy#8]
You ned to use the ["Authorization code" grant type](https://dev.netatmo.com/apidocumentation/oauth#authorization-code) ... I'm currently adjusting ioBroker-netatmo for it ... maybe you can do the same logic

**Comment by Homemade-Disaster** [comment]
New Release 2.0.1 with OAuth2 authentication is now available

**Comment by ioyeti777** [comment]
Top, now it runs great. Many thanks for the work.
